import type { Vehicle } from './types';

export const vehicles: Vehicle[] = [
  {
    id: 'civic-2023',
    make: 'Honda',
    model: 'Civic',
    year: 2023,
    price: 25000,
    bodyStyle: 'Sedan',
    mileage: 15000,
    engine: '1.5L I-4',
    transmission: 'Automatic',
    fuelType: 'Gasoline',
    exteriorColor: 'Silver',
    interiorColor: 'Black',
    numberOfSeats: 5,
    features: ['Apple CarPlay', 'Android Auto', 'Lane Keeping Assist'],
    description: 'A reliable and fuel-efficient sedan, perfect for daily commuting.',
    images: [{ id: 'sedan-1', alt: 'Silver Honda Civic' }, { id: 'sedan-interior-1', alt: 'Interior of Honda Civic' }],
  },
  {
    id: 'rav4-2022',
    make: 'Toyota',
    model: 'RAV4',
    year: 2022,
    price: 32000,
    bodyStyle: 'SUV',
    mileage: 22000,
    engine: '2.5L I-4',
    transmission: 'Automatic',
    fuelType: 'Hybrid',
    exteriorColor: 'Blue',
    interiorColor: 'Gray',
    numberOfSeats: 5,
    features: ['All-Wheel Drive', 'Sunroof', 'Blind Spot Monitor'],
    description: 'Versatile and spacious hybrid SUV with excellent fuel economy.',
    images: [{ id: 'suv-1', alt: 'Blue Toyota RAV4' }, { id: 'suv-interior-1', alt: 'Interior of Toyota RAV4' }],
  },
  {
    id: 'f150-2021',
    make: 'Ford',
    model: 'F-150',
    year: 2021,
    price: 45000,
    bodyStyle: 'Truck',
    mileage: 35000,
    engine: '3.5L V6',
    transmission: 'Automatic',
    fuelType: 'Gasoline',
    exteriorColor: 'Red',
    interiorColor: 'Black',
    numberOfSeats: 5,
    features: ['Towing Package', 'Pro Power Onboard', 'Large Touchscreen'],
    description: 'A powerful and capable truck designed for work and play.',
    images: [{ id: 'truck-1', alt: 'Red Ford F-150' }, { id: 'truck-2', alt: 'Black Ford F-150 at a worksite' }],
  },
  {
    id: 'mustang-2023',
    make: 'Ford',
    model: 'Mustang',
    year: 2023,
    price: 48000,
    bodyStyle: 'Coupe',
    mileage: 8000,
    engine: '5.0L V8',
    transmission: 'Manual',
    fuelType: 'Gasoline',
    exteriorColor: 'Black',
    interiorColor: 'Red',
    numberOfSeats: 4,
    features: ['Performance Package', 'Leather Seats', 'Digital Instrument Cluster'],
    description: 'Iconic American muscle car with thrilling performance and style.',
    images: [{ id: 'coupe-1', alt: 'Black Ford Mustang' }, { id: 'coupe-interior-1', alt: 'Dashboard of Ford Mustang' }],
  },
  {
    id: 'miata-2022',
    make: 'Mazda',
    model: 'MX-5 Miata',
    year: 2022,
    price: 30000,
    bodyStyle: 'Convertible',
    mileage: 12000,
    engine: '2.0L I-4',
    transmission: 'Manual',
    fuelType: 'Gasoline',
    exteriorColor: 'White',
    interiorColor: 'Tan',
    numberOfSeats: 2,
    features: ['Retractable Hardtop', 'Bose Audio System', 'Sport-Tuned Suspension'],
    description: 'A fun-to-drive convertible that offers an exhilarating open-air experience.',
    images: [{ id: 'convertible-1', alt: 'White Mazda Miata' }, { id: 'convertible-interior-1', alt: 'Interior of Mazda Miata' }],
  },
  {
    id: 'model3-2023',
    make: 'Tesla',
    model: 'Model 3',
    year: 2023,
    price: 42000,
    bodyStyle: 'Sedan',
    mileage: 18000,
    engine: 'Electric Motor',
    transmission: 'Automatic',
    fuelType: 'Electric',
    exteriorColor: 'White',
    interiorColor: 'White',
    numberOfSeats: 5,
    features: ['Autopilot', 'Panoramic Glass Roof', '15-inch Touchscreen'],
    description: 'A cutting-edge electric sedan with instant acceleration and long range.',
    images: [{ id: 'electric-1', alt: 'White Tesla Model 3 charging' }, { id: 'sedan-2', alt: 'White sedan in studio' }],
  },
  {
    id: 'crv-2022',
    make: 'Honda',
    model: 'CR-V',
    year: 2022,
    price: 31000,
    bodyStyle: 'SUV',
    mileage: 25000,
    engine: '1.5L Turbo I-4',
    transmission: 'Automatic',
    fuelType: 'Gasoline',
    exteriorColor: 'Silver',
    interiorColor: 'Black',
    numberOfSeats: 5,
    features: ['Honda Sensing', 'Heated Seats', 'Power Tailgate'],
    description: 'A compact SUV that is practical, comfortable, and packed with features.',
    images: [{ id: 'suv-2', alt: 'Silver Honda CR-V in forest' }, { id: 'suv-interior-1', alt: 'Spacious interior of an SUV' }],
  },
  {
    id: 'accord-2023',
    make: 'Honda',
    model: 'Accord',
    year: 2023,
    price: 28000,
    bodyStyle: 'Sedan',
    mileage: 9000,
    engine: '2.0L I-4',
    transmission: 'Automatic',
    fuelType: 'Hybrid',
    exteriorColor: 'Black',
    interiorColor: 'Black',
    numberOfSeats: 5,
    features: ['Wireless Apple CarPlay', 'Sunroof', 'Multi-Angle Rearview Camera'],
    description: 'A stylish and sophisticated hybrid sedan offering a smooth and efficient ride.',
    images: [{ id: 'luxury-sedan-1', alt: 'Luxury black Honda Accord' }, { id: 'sedan-interior-1', alt: 'Interior of a luxury sedan' }],
  },
];
